//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ring
    {
        public int RingID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> RingDiamonds { get; set; }
        public string WinOrLose { get; set; }
        public Nullable<System.DateTime> RingTime { get; set; }
        public Nullable<System.DateTime> GameOverTime { get; set; }
        public string Gamemode { get; set; }
    
        public virtual User User { get; set; }
    }
}
